/**
 *  MIT License
 *
 *  Copyright (c) 2017 Richard Moore <me@ricmoo.com>
 *
 *  Permission is hereby granted, free of charge, to any person obtaining
 *  a copy of this software and associated documentation files (the
 *  "Software"), to deal in the Software without restriction, including
 *  without limitation the rights to use, copy, modify, merge, publish,
 *  distribute, sublicense, and/or sell copies of the Software, and to
 *  permit persons to whom the Software is furnished to do so, subject to
 *  the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *  DEALINGS IN THE SOFTWARE.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "SVProgressHUD.h"
#import <ethers/Promise.h>


// @TODO: This can be generated by the build/font-ethers scripts 
#define ICON_NAME_ALERT              @"A"
#define ICON_NAME_SECURITY_CAMERA    @"B"
#define ICON_NAME_CHECKMARK          @"C"
#define ICON_NAME_CAMERA             @"D"
#define ICON_NAME_ACCOUNTS           @"E"
#define ICON_NAME_PRIVACY            @"F"
#define ICON_NAME_FIRES              @"G"
#define ICON_NAME_HAMBURGER          @"H"
#define ICON_NAME_TX_RECEIVED        @"I"
#define ICON_NAME_FLOODS             @"J"
#define ICON_NAME_TX_SENT            @"K"
#define ICON_NAME_LOGO               @"L"
#define ICON_NAME_DAMAGE             @"M"
#define ICON_NAME_THEFT              @"N"
#define ICON_NAME_FAILURE            @"O"
#define ICON_NAME_LOSS               @"P"
#define ICON_NAME_SEARCH             @"Q"
#define ICON_NAME_CONTRACT           @"R"
#define ICON_NAME_SELECTED           @"S"
#define ICON_NAME_FINGERPRINT        @"T"
#define ICON_NAME_CIRCLE_PLUS        @"U"
#define ICON_NAME_CAMERA_ROLL        @"V"
#define ICON_NAME_WALLET             @"W"
#define ICON_NAME_X                  @"X"
#define ICON_NAME_AIRPLANE           @"Y"

#define ICON_NAME_DEVCON_2           @"1"
#define ICON_NAME_ORIGAMI            @"2"
#define ICON_NAME_CLIPBOARD          @"3"
#define ICON_NAME_ACCOUNT            @"4"

//#define FONT_MONOSPACE               @"AmericanTypewriter"
//#define FONT_MONOSPACE_SMALL         @"AmericanTypewriter-Condensed"
#define FONT_MONOSPACE               @"Menlo-Bold"
#define FONT_MONOSPACE_SMALL         @"Menlo-Regular"
#define FONT_NORMAL                  @"HelveticaNeue"
#define FONT_MEDIUM                  @"HelveticaNeue-Medium"
#define FONT_BOLD                    @"HelveticaNeue-Bold"
#define FONT_ITALIC                  @"HelveticaNeue-Italic"
#define FONT_BOLD_ITALIC             @"HelveticaNeue-BoldItalic"

#define FONT_ETHERS                  @"ethers"


#define ICON_FONT_WALLET            @"\U0000e607"
#define ICON_FONT_IMPORT            @"\U0000e741"
#define ICON_FONT_COPY              @"\U0000e615"
#define ICON_FONT_DONE              @"\U0000e608"
#define FONT_ICONFONT               @"iconfont"

#define CACHEKEY_APP_DATA           @"cachekey_app_data"
#define CACHEKEY_APP_DATA_LANGUAGE  @"cachekey_app_data_language"
#define CACHEKEY_APP_DATA_UNIT      @"cachekey_app_data_unit"
#define UNIT_RMB @"¥"
#define UNIT_DOLLAR @"$"
#define UNIT_RMB_NAME @"CNY"
#define UNIT_DOLLAR_NAME @"USD"

#define COLOR_GREEN [UIColor colorWithRed:81/255. green:161/255. blue:98/255. alpha:1]
#define COLOR_BLUE [UIColor colorWithRed:86/255. green:149/255. blue:237/255. alpha:1]
#define COLOR_PINK [UIColor colorWithRed:175/255. green:53/255. blue:119/255. alpha:1]
#define COLOR_RED [UIColor colorWithRed:190/255. green:55/255. blue:47/255. alpha:1]
#define COLOR_DARK [UIColor colorWithRed:0x4a/255. green:0x4a/255. blue:0x4a/255. alpha:1]
#define COLOR_BACKGROUND [UIColor colorWithRed:0x33/255. green:0x35/255. blue:0x40/255. alpha:1]
#define COLOR_WARNING [UIColor colorWithRed:0xe7/255. green:0x48/255. blue:0x26/255. alpha:1]

//ShowMessage
typedef enum : NSUInteger {
    showTypeNone = 0,
    showTypeStatus,
    showTypeSuccess,
    showTypeError
} showType;
#define showMessage(type,msg) \
{void(^runOnMainThead)(void) = ^{\
if(type == 0)[SVProgressHUD dismiss];\
else if(type == 1)[SVProgressHUD showWithStatus:msg]; \
else if(type == 2)[SVProgressHUD showSuccessWithStatus:msg];\
else [SVProgressHUD showErrorWithStatus:msg];};\
if ( [NSThread isMainThread] )runOnMainThead();\
else dispatch_async( dispatch_get_main_queue(), runOnMainThead );}


@interface MyNavigationBar:UINavigationBar
@end

@interface Utilities : NSObject

+ (NSString*)timeAgo: (NSTimeInterval)timestamp;

+ (UIButton*)ethersButton: (NSString*)iconName fontSize: (CGFloat)fontSize color: (NSUInteger)color;

+ (UILabel*)navigationBarTitleWithString: (NSString*)title;

+ (void)setupNavigationBar: (UINavigationBar*)navigationBar backgroundColor: (UIColor*)backgroundColor;
+ (UINavigationBar*)addNavigationBarToView: (UIView*)view;

+ (UILabel*)navigationBarLogoTitle;

+ (UIImage*)qrCodeForData: (NSData*)data width: (CGFloat)width color: (UIColor*)color padding: (CGFloat)padding;

+ (NSString*)userAgent;

+ (DataPromise*)fetchUrl: (NSString*)url body: (NSData*)body dedupToken: (NSString*)dedupToken;

/* Create a fetching library?
 ApplicationViewController should create it's own provider. Add clone provider?
@property (nonatomic, assign) maximumRequestsPerMinute;
- (DataPromise*)fetchUrl: (NSString*)url;
- (DictionaryPromise*)fetchJSONUrl: (NSString*)url;
- (void)cancelAllRequests;
*/
@end
